name: eats
description: "Eats"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  geolocator: ^12.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.3.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/eats_logo.png
    - assets/img_perfil.png
    - assets/banner.png
