name: eats
description: "Eats"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  geolocator: ^12.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.3.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  geocoding: ^3.0.0
  flutter_rating_bar: ^4.0.1
  http: ^1.2.2
  google_generative_ai: ^0.4.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/eats_logo.png
    - assets/img_perfil.png
    - assets/banner.png
    - assets/logo_white.png
    - assets/icons/google_icon.png
    - assets/icons/upload_icon.png
    - assets/icons/stat_minus_icon.png
    - assets/icons/icon.png
    - assets/icons/mini_icon.png
    - assets/food_img.jpg
    - assets/star.png
    - assets/hungry.png
    - assets/icons/brilha.png